name: CI

on:
  push:
        branches: [secrets]
env:
#   NODE_VERSION: 24
  NODE_ENV_TEST: ${{ secrets.NODE_ENV_TEST }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print node version
        run: |
          echo "Node version: $NODE_ENV_TEST"

      - name: Show gitHub variables
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "SHA:" $GITHUB_SHA
